apiVersion: v2
name: gomenhashai
description: |
  Keep your Kubernetes cluster safe by ensuring all container's images use digests from a trusted set. GomenHashai verifies image integrity and gently apologizes as it gracefully denies or terminates pods that don't meet the standard. Gomen Hashai~ ğŸ™‡

  Built with security ğŸ›¡ï¸ in mind, ğŸ£ GomenHashai ships with strong default protections.
type: application
version: 1.3.2
appVersion: "v1.3.1"
keywords:
  - security
  - integrity
  - admission-webhook
  - image-digest
home: https://github.com/GomenHashai/GomenHashai
sources:
  - https://github.com/GomenHashai/GomenHashai
maintainers:
  - name: MarcAntoineRaymond
    url: https://github.com/MarcAntoineRaymond
icon: https://raw.githubusercontent.com/GomenHashai/GomenHashai/main/logo/GomenHashai_NoBg_NoText.png
