apiVersion: v2
name: gomenhashai
description: |
  Keep your Kubernetes cluster safe by ensuring all container's images use digests from a trusted set. GomenHashai verifies image integrity and gently apologizes as it gracefully denies or terminates pods that donâ€™t meet the standard. Gomen Hashai~ ğŸ™‡

  Built with security ğŸ›¡ï¸ in mind, ğŸ£ GomenHashai ships with strong default protections.

  ## ğŸš€ Quick Start

  Deploy in warn mode:

  ```sh
  helm install gomenhashai gomenhashai --repo https://marcantoineRaymond.github.io/GomenHashai \
    --namespace gomenhashai-system \
    --create-namespace \
    --set config.validationMode="warn"
  ```

  ---

  ## ğŸ£ Usage

  GomenHashai uses **Kubernetes admission webhook** to validate and optionally mutate pod specifications to ensure all container images use **immutable digests** instead of mutable tags.
  It helps enforce image provenance and strengthen your supply chain security posture.
  It has many more features.

  See the [Full Documentation](https://github.com/MarcAntoineRaymond/GomenHashai).
type: application
version: 1.2.1
appVersion: "v1.3.0"
keywords:
  - security
  - integrity
  - admission-webhook
  - image-digest
home: https://github.com/MarcAntoineRaymond/GomenHashai
sources:
  - https://github.com/MarcAntoineRaymond/GomenHashai
maintainers:
  - name: MarcAntoineRaymond
    url: https://github.com/MarcAntoineRaymond
icon: https://raw.githubusercontent.com/MarcAntoineRaymond/GomenHashai/main/logo/GomenHashai_NoBg_NoText.png
