apiVersion: v2
name: gomenhashai
description: GomenHashai guarantee images integrity in your k8s cluster by adding digests from a trusted set to your pods. It will also apologize for denying and gently terminating pods that does not use a trusted digest. ğŸ£GomenHashai!
type: application
version: 0.1.0
appVersion: "v0.1.0"
