{{- if .Values.globalPullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gomenhashai.fullname" . }}-global-pull-secrets
  labels:
    {{- include "gomenhashai.labels" . | nindent 4 }}
stringData:
  pullSecretsCredentials.yaml: |
    {{- .Values.globalPullSecrets | toYaml | nindent 4 }}
type: Opaque
{{- end }}